# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91923946475322c1b47346ccf7a57b8cd249c4a1c209c13d8f94164325207ff901d39b1080b278709b9301b199f4d717a34393c3aabc0796f7c365c30c74076

test:
  secret_key_base: 06b751214bf85944b5c24934e6c3f123752e9e899dba4acf5c0d3b2e55428cf1681d88ad3aec553f2c4a98a3db6de0dade208b4bced77c1ac431727e397be296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
